### ISSUE TITLE
Create Labels For Contact Form

### ISSUE THREAD

**Issue by gleekzorp** [code-experiment/code-experiment-website#85]
**Is your feature request related to a problem? Please describe.**

When I first go to the contact form based on the placeholder text I understand what each input is for.  Once I start typing in the input field we don't have labels.  This can be confusing for the user.

**Describe the solution you'd like**

Add labels that would also help with accessibility.
- Name
- Email
- Enter your question here

**Comment by Tye-Hadfield** [comment]
I can do this one!
